name: KiARC Repository Manager

on:
  push:
    branches:
      - dev
      - mvp-testing
      - "*"
    paths-ignore:
      - "README.md"
      - "gradle/**"
      - "*.vpr"
      - "*.sh"
      - "*.txt"
jobs:
  kiarc-repository-manager:
    name: KiARC Repository Manager
    runs-on: ubuntu-latest
    steps:
      - uses: KiARC/KiARC-Repository-Manager@main